### ISSUE TITLE
Bug: The chef binary (either `chef-solo` or `chef-client`) was not found on ...

### ISSUE THREAD

**Issue by SchumacherFM** [EcomDev/vagrant-magento#1]
Hey Ivan,

thanks for providing this repo! Great work and complicated to. 

I've just cloned it and and `vagrant up` and it ends with this result:

```
Vendoring yum-epel (0.5.1) to /Users/osxuser/.berkshelf/default/vagrant/berkshelf-20140930-71861-dw7nro-default/yum-epel
Vendoring yum-mysql-community (0.1.10) to /Users/osxuser/.berkshelf/default/vagrant/berkshelf-20140930-71861-dw7nro-default/yum-mysql-community
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Installing rsync to the VM...
==> default: Rsyncing folder: /Users/osxuser/Sites/vagrant-magento/ => /Users/osxuser/Sites/vagrant-magento
==> default: Mounting shared folders...
    default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks => /Users/osxuser/.berkshelf/default/vagrant/berkshelf-20140930-71861-dw7nro-default
==> default: Running provisioner: chef_solo...
The chef binary (either `chef-solo` or `chef-client`) was not found on
the VM and is required for chef provisioning. Please verify that chef
is installed and that the binary is available on the PATH.
osxuser at osxhost in ~/Sites/vagrant-magento on master
```

Any idea?
Thanks in advance!

**Comment by IvanChepurnyi** [comment]
Sorry, I didn't create README file. For making this work: 
you need to run the following commands one time on your computer:
`vagrant plugin install vagrant-berkshelf --plugin-version=2.0.1`
`vagrant plugin install vagrant-omnibus`
`vagrant plugin install vagrant-hostmanager`

Recommended additional plugins:
`vagrant plugin install vagrant-cachier`

**Comment by SchumacherFM** [comment]
Thanks Ivan!

Installed the plugins and run it again with the following error in a ruby script:

```
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: [2014-09-30T23:39:11+00:00] INFO: *** Chef 11.16.2 ***
==> default: [2014-09-30T23:39:11+00:00] INFO: Chef-client pid: 3529
==> default: [2014-09-30T23:39:14+00:00] INFO: Setting the run_list to ["recipe[mysql::server]", "recipe[magento::application]", "recipe[magento::redis]", "recipe[magento_varnish::default]"] from CLI options
==> default: [2014-09-30T23:39:14+00:00] INFO: Run List is [recipe[mysql::server], recipe[magento::application], recipe[magento::redis], recipe[magento_varnish::default]]
==> default: [2014-09-30T23:39:14+00:00] INFO: Run List expands to [mysql::server, magento::application, magento::redis, magento_varnish::default]
==> default: [2014-09-30T23:39:14+00:00] INFO: Starting Chef Run for magento
==> default: [2014-09-30T23:39:14+00:00] INFO: Running start handlers
==> default: [2014-09-30T23:39:14+00:00] INFO: Start handlers complete.
==> default: [2014-09-30T23:39:21+00:00] INFO: WindowsPackage lightweight resource already initialized -- overriding!
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb
==> default: ================================================================================
==> default:
==> default:
==> default: Chef::Exceptions::ValidationFailed
==> default: ----------------------------------
==> default: Option uid must be a kind of [Integer, Symbol]!  You passed "".
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb:37:in `block (2 levels) in from_file'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb:36:in `each_pair'
==> default:
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb:36:in `block in from_file'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb:35:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/magento/recipes/application.rb:
==> default:
==> default:
==> default:  30:
==> default:  31:  Chef::Mixin::DeepMerge.deep_merge!(node[:magento][:application][:database_options].to_hash, database_options)
==> default:  32:
==> default:  33:  node.default[:magento][:application][:database_options] = database_options
==> default:  34:
==> default:  35:  magento_application node[:magento][:application][:name] do
==> default:  36:    node[:magento][:application].to_hash.each_pair do |key, value|
==> default:  37>>     send(key.to_sym, value)
==> default:  38:    end
==> default:
==> default:  39:  end
==> default:  40:
==> default:
==> default:
==> default: [2014-09-30T23:39:22+00:00] ERROR: Running exception handlers
==> default: [2014-09-30T23:39:22+00:00] ERROR: Exception handlers complete
==> default: [2014-09-30T23:39:22+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2014-09-30T23:39:22+00:00] ERROR: Option uid must be a kind of [Integer, Symbol]!  You passed "".
==> default: [2014-09-30T23:39:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by IvanChepurnyi** [comment]
This is because uid is a mapping of your host machine and guest machine application user. If it equals to `:auto` than it will automatically map it. If you don't want to specify it, just remove the whole element from configuration, then it will be set to null and so won't be processed by chef recipe.

Better if you submit your magento.json so I can give you direct advice what is wrong.

**Comment by SchumacherFM** [comment]
I've only changed the name and main_domain in your magento.json file. Also added `"uid": ":auto"`.

```
{
    "magento": {
        "application": {
            "name": "zookal",
            "uid": ":auto",
            "main_domain": "zookal.dev",
            "directory": "<%=current_path%>",
```

**Comment by IvanChepurnyi** [comment]
Hmm. Are you using *nix based system as a host?

**Comment by SchumacherFM** [comment]
Oh yes I'm on OSX 10.9.5
